### ISSUE TITLE
Feature requests on searchable reference selector

### ISSUE THREAD

**Issue by Maismaus** [bsgriggs/mendix9-searchable-reference-selector#1]
Hi Benjamin,

Great job on this widget, it's exactly what I was looking for in my project! Thanks!🙏 

I have two suggestions. Firstly, the dropdown doesn't update its position when you scroll the page. There should probably be a scrollListener that calls updatePosition so the dropdown doesn't stick to its x and y but rather adjusts to the position of the input field. Secondly, it'd be great if we could configure an 'On Click' action for the badge, so we could let the user open the corresponding edit page for the referenced object. 
Cheers,
Marius

**Comment by bsgriggs** [comment]
Hi Marius,

Thank you for the feedback! I haven't tried the scrollListener before, but it'll be worth a shot. For the second, this is a great idea! I'll do some experiments to see if the pluggable widget library will let me do this.

Thank you!
Ben

**Comment by Boris-Scharinger** [comment]
Hi Benjamin, in case you'd like to be able to support the horizontal rendering of radio buttons, I did it this way:

.mx-name-searchableReferenceSelectorMx92.radio-button-horizontal .srs-list {
    display:flex;
    flex-direction: row;
}
and added the class radio-button-horizontal to the widget properties. Works nicely and had been a missing piece to finally kick the legacy widget RadioButtionAssociations out.
Cheers, Boris

**Comment by bsgriggs** [comment]
@Maismaus I have a fix for the scroll behavior and on-click badge coming soon. I've got the code ready ~ only needs just a bit more testing.

@Boris-Scharinger Nice find! Do you have a picture of what the horizontal radio buttons look like (so I can better understand the use case)?

**Comment by bsgriggs** [comment]
v1.4 
- changed text settings to textTemplates to support different languages
- the dropdown popup now updates its position when scrolling
- added the ability to set an action when a reference set's badge is selected
