### ISSUE TITLE
Difficult upgrade

### ISSUE THREAD

**Issue by odi76** [bsgriggs/mendix9-searchable-reference-selector#10]
I would like to upgrade from v1.5.5 to v2.4.0 but I run to the problem that I would have to reconfigure all instances because all upgraded instances would be set as Enumeration selector instead of the "original" Reference set selector. Please find the screenshots of original and new (default) properties.
Since I have almost 200 instances, this upgrade would require quite a lot resource to perform. Could you control the upgraded property to inherit the original configuration.  Of course, any other suggestion is also welcome. 

**Original properties:**
![SearchableSelector_OriginalConfig](https://user-images.githubusercontent.com/19372170/233138823-95fbafcb-916c-4764-b072-a79fa1e1ee90.png)

**Updated properties:**
![SearchableSelector_UpdatedConfig](https://user-images.githubusercontent.com/19372170/233138842-ee693b16-1034-4d4d-a2dd-8a0a770687dc.png)

**Comment by bsgriggs** [comment]
Hi there,

Unfortunately, there isn't a solution that doesn't require manual updates. The widget has had many structural improvements over v1.5 -> v2.0.

I've built [this](https://github.com/bsgriggs/mendix9-searchable-reference-selector/files/11276475/mendix.SearchableReferenceSelectorMxNine.mpk.zip) version for you with the default Selection Type as Reference. This should reduce the number of manual updates, but you will still need to manually update the Reference and Selectable Condition options.

![Screenshot 2023-04-19 at 2 27 57 PM](https://user-images.githubusercontent.com/47681665/233167030-abfbca22-83cd-41f4-87bd-8dc953fad2d4.png)

**Comment by odi76** [comment]
Does not sound good! However, thanks for the specific edition.
