### ISSUE TITLE
Can we make placeholder disappear on Reference Set once a selection is made?

### ISSUE THREAD

**Issue by erickomorek** [bsgriggs/mendix9-searchable-reference-selector#12]
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/2341243/25a572db-bdc2-4136-b8fa-2b65c08707d1)

It would be nice to have the option to remove the placeholder (Search...) once a selection was made on a Reference Set for a cleaner and more compact look. This would be similar to how it already works for a single Reference or Enum selection.

**Comment by bsgriggs** [comment]
Hi Eric, 

In release v4.0.0, I've added "Compact?" to the options on the Style tab. Please let me know what you think.

**Comment by erickomorek** [comment]
This is great, thank you so much!

-Eric
