### ISSUE TITLE
Reactive pop-up to close the (+X) items

### ISSUE THREAD

**Issue by viktororosso** [bsgriggs/mendix9-searchable-reference-selector#13]
Hi,

Thanks for this widget, it is really useful. It's almost sad that Mendix doens't have an easy but flexible filter like this in their datagrid...

I would like do a suggestion for an enhancement:
I would like the (for example) '(+3)' text after the selected items to be reactive such that I can click on it, see the list with the 3 items and decide which one I would like to close as well. 

This because I don't want my search fields to become to big, as I have plenty of them and I don't want half of my screen to be covered with filters. So 1 line (or 2 lines max) would be nice with still the ability to be able to close any selected item.

Best regards,

Viktor

**Comment by bsgriggs** [comment]
Hi Viktor,

I love the idea! I'm not completely sold on having a second popup. I feel it would be information overload. But being able to see what is in the +3 would be beneficial. I'll give it some thought. 

As a minimum, I could add a standard MxAction for clicking the text. It would look the same as the 'On badge click'. You would make a Mendix popup page that shows all of the values for the reference.

**Comment by viktororosso** [comment]
Hi Benjamin,

Great, I think that would work! Thanks for considering the enhancement. Any idea when we can expect this to be implemented in the widget?

**Comment by bsgriggs** [comment]
Released to the market place as version 4.1.0
