### ISSUE TITLE
I cant use this Widget in Mendix 10.1.1 

### ISSUE THREAD

**Issue by AndreasLHIND** [bsgriggs/mendix9-searchable-reference-selector#14]
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%2C%20constructor%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings. Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%2C%20constructor%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zo (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:56118)
    at e (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:61117)
    at xs (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:72732)
    at Cc (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:121422)
    at wl (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:108763)
    at bl (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:108691)
    at vl (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:108554)
    at al (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:105361)
    at ll (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:105750)
    at Ur (http://localhost:8080/mxclientsystem/mxui/mxui.js?638272598314024405:34:46625)

**Comment by bsgriggs** [comment]
Hi,

I was unable to reproduce this in 10.1.1. Are you using the latest version of the widget? Can you please provide screenshots of your settings and any details that can help be reproduce this?
![Screenshot 2023-08-10 at 10 14 11 AM](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/47681665/ad3e0833-5223-417a-8dce-3fcc0b2b415c)

**Comment by AndreasLHIND** [comment]
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/89c9923f-6428-4fec-8b4b-533fdccdd83f)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/b5908967-2acc-457d-bec8-c6d01ed393d1)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/29dc1a57-473d-411f-9e32-dfed76ac985d)

**Comment by AndreasLHIND** [comment]
Hi i hope you can help me

**Comment by bsgriggs** [comment]
Can you please include the other tabs as well

**Comment by AndreasLHIND** [comment]
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/41c81631-4f5b-4edf-a228-5bc3c3f8dbf7)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/dd9335a6-40ec-46d3-a134-dc6ccd772232)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/e04e5870-1756-4938-8a8f-59026090ee55)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/a2c3eabb-ed66-40f0-9e73-4f4f4d32aafc)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/49cbe1c7-b58a-4526-a62d-ca260ff7e227)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/141933968/6f9f4f92-55fd-4274-8553-a2a6fa6d520b)

**Comment by bsgriggs** [comment]
It seems to be an issue with filtering on an integer with Option Content Type Text/HTML. I'm working on a fix right now. 

You should be able get around it for now by using Option Content Type Expression and then toString($currentObject/UNumber)
<img width="557" alt="Screenshot 2023-08-10 at 11 11 41 AM" src="https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/47681665/635b0e1e-9282-4b9d-a92d-75ea339ce533">


Per your data model, I would challenge that you shouldn't use an integer for that field. _Typically_ you should only use an integer if you need to perform a mathematically calculation. Things like EmployeeIDs should be strings.

**Comment by bsgriggs** [comment]
V4.0.1 has been released to the [marketplace](https://marketplace.mendix.com/link/component/116917) and on [GitHub](https://github.com/bsgriggs/mendix9-searchable-reference-selector/releases/download/v4.0.1/mendix.SearchableReferenceSelectorMxNine.mpk)
