### ISSUE TITLE
Searching enumeration "Contains" seems to work only for the 1st word

### ISSUE THREAD

**Issue by NOA-Alex** [bsgriggs/mendix9-searchable-reference-selector#16]
I have many enumerations like with a label like "CAD - Canadian Dollar", "AUD - Australian Dollar", etc. While the enumeration key is just the ISO code "CAD", "AUD", etc. Same for countries, languages, and so on.
When I search the enumeration with the option "contains" it seems to work only for the enum key (which is usually not visible for the user, but not for the label. I tried also to remove spaces or the "-" out of the enum label. That also did not help me to search for anything in the label which is not in the enum key. Can you check that?
I am using Mendix 10.2.0 and version 4.1.1 of your widget.

**Comment by bsgriggs** [comment]
Hi Alex,

Can you please include screenshots of your widget's settings, so I can attempt to reproduce the issue?

**Comment by NOA-Alex** [comment]
Thanks for your quick reply.
Please take a look at these:
![Enum Screenshot_20230908085514](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/21526035/3b615847-636f-4a81-a480-5a0f22e99669)
![Settings Screenshot_20230908085403](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/21526035/efffc07f-e5a0-49ee-99d1-eee65f7de2b0)
![Attribute Screenshot_20230908085449](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/21526035/e8179c87-872c-4902-920c-ecb5d4f723ef)

**Comment by bsgriggs** [comment]
I've released v4.2.0 to GitHub and the Marketplace with the fix. The code was filtering against the enumeration's Name/Key instead of the Caption.

**Comment by NOA-Alex** [comment]
You are the best @bsgriggs !
Just updated, tested and it works :-)
