### ISSUE TITLE
Improved performence by not pre-loading reference dropdown options on page load

### ISSUE THREAD

**Issue by NOA-Alex** [bsgriggs/mendix9-searchable-reference-selector#17]
Probably more an enhancement than a bug, but it would be great if there could be a checkbox for references to prevent the pre-loading of the dropdown till the user clicks the first time on it.
Currently if I have an editable list (for example DataGrid2) with 20 shipping addresses (or similar) with each row having a searchable selector to link that address to a contact/person then each searchable selector sends on page load 1 request to the database for the first 20 options in the dropdown menu. Which pulls 20*20=400 records from the DB on page load. Visible in the browser as 20 separate xas calls.
I can set the Max Limit to (for example) 2, then I pull only 2*20 = 40 records from the DB (though still 20 xas calls). But then when I actually open one searchable selector to search/change a reference then I see only 2 entries. And if I click on "Load More" then I see just additional 2 entries.

Adding a checkbox to enable or disable pre-loading of the widget dropdown menus on page load would allow to pre-load zero. And then when a user clicks on the widget then the first time the Max Limit (eg 20) records get loaded. And on search then the next records. Etc.

**Comment by bsgriggs** [comment]
Good Idea! I'll see what I can do.

**Comment by NOA-Alex** [comment]
@bsgriggs you are the best! Looking forward to this release then.

**Comment by bsgriggs** [comment]
Hi! I've added this as **Load Data On "Open Dropdown"** in the Style tab as part of Marketplace release v5.0.0. Please let me know if you encounter any issues.

![styleSet](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/47681665/e9b3cf87-d32d-44a6-949f-fda53373f8dc)

**Comment by NOA-Alex** [comment]
Perfect @bsgriggs this is exactly what I have been looking for. And during the first tests it seems to work flawlessly!
