### ISSUE TITLE
Suggestion: Clear the filter.

### ISSUE THREAD

**Issue by I8NHJ** [bsgriggs/mendix9-searchable-reference-selector#18]
In my case, the selectable objects are fed by a Microflow that selects objects from a database over an association.
It would be beneficial to automatically clean the search area when the microflow is called. This way the user has visual feedback that the previous filter is not valid anymore.

**Comment by bsgriggs** [comment]
I'm not sure I understand your use case. The search text should clear automatically if the user isn't focused on the input anymore. 

If the user is still focused on the input, I shouldn't clear the search text because the user is actively searching ~ entering search text re-runs the data source.

**Comment by I8NHJ** [comment]
Hi there, thanks for the quick answer. I understand my request was a little foggy. Please bear with me while I'm trying to explain what is going on. My original project has two reference selectors. The first one allows the selection of job sites, and the second one selects elements belonging to the selected job site.  There is a non-persistable object with association to the jobsite and cells table permitting the use of reference selectors. 
Selecting a job site from the first reference selector refreshes the non-persistable table which is the data source for the second reference selector.
With this widget, it is not possible to use non-persistable tables as the data source, so the workaround was to use a microflow to filter out the data. This turns out in an inconsistency between the data and the view until the focus is set back to the widget triggering the microflow.

Please look at the screenshots showing the behavior with the standard reference selector and the searchable reference selector:
![snip1](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/24840495/2371482b-5151-46de-984f-fe4c269ba4be)
![snip2](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/24840495/4747c428-4ba7-4947-a306-09992d2304e4)
![snip3](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/24840495/5d9a9058-b374-4bf0-a47f-7ab27ddd1f81)
![snip4](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/24840495/74839fbd-0d8e-477d-b001-ceac1fc2b1fa)

**Comment by bsgriggs** [comment]
hmm I think I understand now. Have you tried using the OnChange action for the Jobsite dropdown to set the Cell Designation to empty?

**Comment by I8NHJ** [comment]
That worked, thank you!

Being able to use a non-persistable data source for this widget, along with other sources, will be the perfect solution, though, and will match the original options available for the reference selector.

**Comment by bsgriggs** [comment]
It is not possible to select non-persistent data sources for Type Database or Type XPath because non-persistent data does not exist in the database at all. Non-persistent data has to come from a Microflow or a Nanoflow
