### ISSUE TITLE
Only attributes ... error with version 5.0.0

### ISSUE THREAD

**Issue by I8NHJ** [bsgriggs/mendix9-searchable-reference-selector#19]
I'm getting the 'Only attributes of type AutoNumber, String, Integer, Long, Decimal are allowed here' error.
My configuration is different from what is listed in the release note under breaking changes:

![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/24840495/ed66e3d7-9ee3-4615-993c-d280eb80c2f3)

How should I proceed to fix this?
Thank you.

**Comment by bsgriggs** [comment]
Are either of the search attributes an enumeration? If so, then you need to switch Search Mode to Client Side and then enter the expression below the Option Content Type.

**Comment by I8NHJ** [comment]
CurrentPhase is an enumerator.
Should 'Option content type' be 'Expression' or can stay 'Custom'?
What expression should be entered to match those search criteria?

**Comment by bsgriggs** [comment]
it can be either Expression or Custom.

The expression for Option Content Type "Custom" in client side mode is used to search against. Basically think of it as a string that represents the data in for each option. When the widget does the filtering, it will check if that string matches the search criteria.

**Comment by I8NHJ** [comment]
I get that, what I do not understand is how to write this expression.  Should it just be the list of variables to search against or something else? Maybe an example helps.

**Comment by bsgriggs** [comment]
if you're doing custom content, you can just do something like $currentObject/UniqueCellId_link + ' ' + toString($currentObject/CurrentPhase)

**Comment by I8NHJ** [comment]
Thank you for helping me out with this.

**Comment by bsgriggs** [comment]
You're welcome!
