### ISSUE TITLE
Filtering Enumeration is not working properly

### ISSUE THREAD

**Issue by juliet-theaquarium** [bsgriggs/mendix9-searchable-reference-selector#20]
Hi, 
I have tried to exclude an enumeration value from the dropdown but it is still visible when I run the app. 
I have also tried using 'include' option and but then nothing is showing in the dropdown.

Can you please have a look and let me know if I'm missing some of the steps to make it work? Thank you!

Configuration of widget:
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/137753613/2d9b2adc-8251-44bf-9e27-27a7f88fe901)

Enumeration:
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/137753613/4ae57c3a-0e49-4430-8757-f444543e3b66)

What's currently showing when the app is run:
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/137753613/9baaaf3a-3190-4bc8-bf5a-d009e9d75e63)

**Comment by bsgriggs** [comment]
Hi,
I was unable to reproduce the issue. Is it possible that the Data base attribute 'PermissionLevel' does not use 'ENUM_UserData_AccessType' but another enumeration with similar captions? Also, what version of Mendix are you using?

Widget Config:
![Screenshot 2023-12-11 at 10 32 06 AM](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/47681665/c804db8f-cd7e-4ee9-88a8-914120f6630f)

Enumeration:
![Screenshot 2023-12-11 at 10 31 29 AM](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/47681665/8b3c5352-f3dd-4369-b210-bcea4b97bebd)

App UI:
![Screenshot 2023-12-11 at 10 32 31 AM](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/47681665/7b786aeb-bfe8-4481-b84d-75e465fd2a72)
