### ISSUE TITLE
Searched text persist in widget when using search type "By data source microflow"

### ISSUE THREAD

**Issue by Pendzik** [bsgriggs/mendix9-searchable-reference-selector#21]
Hi,
As mentioned in title i had encounter issue when using widget with microflows. Basically when creating instance of widget where you use data source microflow and searching method also need to have search type microflow, then after typing and selecting something previously entered text remain in control (in background association is set correctly, so probably only cleaning of field is missing) and covers newly selected value. Issue is reproduceable in [https://widgettesting105-sandbox.mxapps.io/p/searchable-selector-test-scripts](url)

Sample configuration:
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/37659599/2ba68f75-4111-4c29-88b6-daedbea8ca21)

Issue in test enviroment:
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/37659599/add06813-038d-4264-8b3c-50d18c929a77)
![image](https://github.com/bsgriggs/mendix9-searchable-reference-selector/assets/37659599/806589a2-b50e-494e-bbef-d92b54cf6b39)

**Comment by bholliger** [comment]
Hi,
If you have a defined a microflow with a change activity in the on change event with refresh enabled it will lead to this issue.
It would be interesting whether this is the case in the test environment as well.

**Comment by bsgriggs** [comment]
Hi there, 
Typically I use the on leave action to reset the search text and pagination back to default values. Hope this helps.
