### ISSUE TITLE
OnChange is not triggered when clearing the search

### ISSUE THREAD

**Issue by AkesslerACN** [bsgriggs/mendix9-searchable-reference-selector#22]
Hello everyone, 
when you have options selected and you clear the selection either by clicking the clearable icon or clicking on all selected entries, the On Change event is not triggered. 

If you have multiple options selected and you deselect all except one, the On Change event will be triggered

**Comment by bsgriggs** [comment]
Hi there, 
The on change is working as expected in the test app https://widgettesting105-sandbox.mxapps.io/p/searchable-selector-test-scripts
Do you have any further details that could assist reproducing this issue?

**Comment by AkesslerACN** [comment]
Hi Benjamin, 

for example I have selected here two countries:
![image](https://github.com/user-attachments/assets/6ea97e01-2aef-4052-8b2b-1d75a29ee40d)

When I click on on the X next to Denmark to remove it, the OnChange is triggered. But when I click afterwards on X on Canada, the OnChange is not triggered.  Same behaviour if I deselect them via the checkbox

Also when I click on the X on the far right, to clear the whole selection, the OnChange is not triggered. 

Application is running on Mendix 9.24.6

please find below the configuration of the widget in my app: 
![image](https://github.com/user-attachments/assets/32b3dfe6-2533-445f-9f5e-6425ddcfe95a)
![image](https://github.com/user-attachments/assets/e112821b-cb2a-442a-a0a0-67c2e84e18eb)
![image](https://github.com/user-attachments/assets/6b952b33-3357-4acf-a58f-5d700505fbbc)
![image](https://github.com/user-attachments/assets/3e70c16a-5135-470a-b99d-f0e2e68404ea)

**Comment by AkesslerACN** [comment]
And one thing I just noticed: 
If I turn off Clearable in the Customizations tab, you cannot deselect the last remaining item via the checkbox. 
Here I am not sure if that is actually a bug, because the description of the option is not very clear.

**Comment by AkesslerACN** [comment]
Update: Seems to be a problem with Nanoflow as OnChange Event. 
When I select Microflow, the OnChange is triggered everytime a change has happend. 

Would require the nanoflow though, because I want to show a loading bar for the calculations happening after selecting a value

**Comment by bsgriggs** [comment]
Hi there, 
Please try the [latest release](https://github.com/bsgriggs/mendix9-searchable-reference-selector/releases/tag/v5.4.0) to see if that fixes your issue. 

I was not able to reproduce your issue in my test app (mx 9.24.5), so it may be a bug with 9.24.6. If the latest release does not fix your issue, try upgrading your app in a test branch.

**Comment by AkesslerACN** [comment]
Hi Benjamin, 

thanks for this new release. 
I can confirm that the bug has been solved for me now with the widget release 5.4.0 in MX 9.24.6

**Comment by bsgriggs** [comment]
Hi there again,
Please update to [v5.4.1](https://github.com/bsgriggs/mendix9-searchable-reference-selector/releases/download/v5.4.1/mendix.SearchableReferenceSelectorMxNine.mpk). I had left a console.log() in the code by mistake.
