### ISSUE TITLE
No progress bar on event microflows

### ISSUE THREAD

**Issue by HansRoksSilvasoft** [bsgriggs/mendix9-searchable-reference-selector#23]
On the Microflow Settings screen, the entire "Execution" part is missing. So when setting a "Call a microflow" event, there is no option to add a progress bar for example, leading to weird user interactions.

My on change microflow takes a bit longer and the user is unaware of this.

**Comment by bsgriggs** [comment]
This is platform behavior that the widget cannot change. 

You can get around this by using a nanoflow that has the Show Progress and Hide Progress actions from nanoflow commons.
