### ISSUE TITLE
Search filter text getting cleared as soon as we type

### ISSUE THREAD

**Issue by Teja220812** [bsgriggs/mendix9-searchable-reference-selector#4]
Text getting cleared while applying filter criteria in the widget. 
You can find issue happening in the widget from sandbox link as well.
https://widgettesting105-sandbox.mxapps.io/p/searchable-reference-selector
![image](https://user-images.githubusercontent.com/116641033/197768123-bb36f35d-f547-49e7-a8d3-c2783d6f1b20.png)

**Comment by bsgriggs** [comment]
Hi,
I was able to reproduce this in the environment but not in my local. And my local has had many changes since the version deployed.

Would you be able to send screenshots of all the settings for the widget in your test project to help me debug?

**Comment by bsgriggs** [comment]
Hi,
The issue only seems to occur if there are too many options rendering at a time. Try using the **Max Items** setting to limit how many options are rendered without searching. In my test 100 Max Items were enough to prevent the issue.

**Comment by Teja220812** [comment]
Hi,
bsgrigs,
Thanks for update ,Please let us know which  control we  need to use if we have more options to load..

**Comment by bsgriggs** [comment]
Sure! In the General tab there is an integer called "Max Items". Set this limit and the widget will only show the first x number of records. When the user searches, all records will still be considered. 

**Be sure to also update to version 1.4.1 in the marketplace, there was a bug with the "More Results Text" field**
![Screen Shot 2022-10-28 at 1 15 31 PM](https://user-images.githubusercontent.com/47681665/198695117-432d10f3-8dad-43fe-bbd3-3a564220b894.png)
