### ISSUE TITLE
No option to hide listview or dropdown (without clearing selection)

### ISSUE THREAD

**Issue by louiseAB97** [bsgriggs/mendix9-searchable-reference-selector#5]
Dear makers of this widget,

Thank you for your efforts, the widget is almost perfect for my intended usage.
However I am missing an option to close the dropdown on listview. In my scenario it is rather user unfriendly that after selecting some options the list cannot close.

Is there any way to circumvent this? Perhaps showing options only after entering a search for instance. 

I am looking forward to any suggestions.

**Comment by bsgriggs** [comment]
Hello,
Can you please attach screenshots, so I can better understand your use case? Both the browser UI and the widget settings in the modeler.

**Comment by louiseAB97** [comment]
![image](https://user-images.githubusercontent.com/44020796/202407412-e1b5a957-9f1b-4e84-adf9-d110f33aa949.png)
![image](https://user-images.githubusercontent.com/44020796/202407479-252842f8-e591-4d31-bd57-a30419d21b37.png)
![image](https://user-images.githubusercontent.com/44020796/202407521-6505fefe-90dc-411b-a60c-471f06cbd491.png)

**Comment by louiseAB97** [comment]
My wish is to only show the options once click on the search bar. And to also be able to close the options again once you press an icon or click outside of the searchbar.

**Comment by louiseAB97** [comment]
The dropdown is also not an option, because the depiction of selected items above the searchbar does not match my wish to display them elsewhere on the page. 
![image](https://user-images.githubusercontent.com/44020796/202408408-6b3ff08f-822b-4ef3-b303-d26cb0e69d1a.png)

**Comment by bsgriggs** [comment]
You can achieve the result I believe you're looking for using the following:
- Update your local widget to version 1.4.2
- Change the Option Text Type to 'Custom'
![Screenshot 2022-11-17 at 10 34 54 AM](https://user-images.githubusercontent.com/47681665/202491032-1f2b6c11-932e-4dcc-8151-7f7b1c19c6b4.png)
- A new container will appear on the Mendix page for you to drop content into
- Add a layout grid with 3 columns for your image, text, and remove button
![Screenshot 2022-11-17 at 10 35 09 AM](https://user-images.githubusercontent.com/47681665/202491669-375065bd-233f-4ad6-a376-62da0881345f.png)
- On the remove button, add a class "remove-btn"
- On one of your application styles add the following. This will make the remove button only display on rows that are already selected
```
.srs-option .remove-btn{
        display: none;
}

.srs-option.selected .remove-btn{
        display: block;
}
```
- run the project and you should see something like this 
![Screenshot 2022-11-17 at 10 59 31 AM](https://user-images.githubusercontent.com/47681665/202495688-ba93b2c4-c98e-4c88-9cc3-fb0bc9f53d1b.png)
