### ISSUE TITLE
Enum attribute represented by key

### ISSUE THREAD

**Issue by odi76** [bsgriggs/mendix9-searchable-reference-selector#6]
In case of enum type attribute the widget presents the key values and not the captions. Searching is also failing.

Is this data type supported?

The following error is logged in browser console during first rendering:
Client] Error: Argument #0 of function "contains" has an incompatible type (Enum != [String, Integer, Long, Decimal]).

**Comment by bsgriggs** [comment]
I would advise against using an enumeration. I will remove the option to select them in a future release.

This widget is for selecting an association to another object, not an enumeration value. I don't know your exact use case, but there would likely be multiple objects with the same enumeration value. In this scenario, you would have multiple options in the dropdown with that same value.

I do like this idea though; I will consider duplicating the widget and making something similar for selecting an enumeration value in the future.

**Comment by odi76** [comment]
In fact, I would select from objects, not from enum values. These object are specified in design-time and so can be represented by enum-type attribute. The reason behind is simple: allow an object to have multiple "enum values". (In Mendix, you cannot assign an attribute with 1+ cardinality.)
So I need the same widget to select associations to another object represented by enum value. I would like to use this (built-in enum object) design pattern since I want to assign multiple enum values to an object. So please do not create a new widget for enum selection. I will not able to use it. I need this widget with supporting enum type at the representation attribute. Thx!

**Comment by bsgriggs** [comment]
Hmm, then I have to ask what benefit are you getting by using an enumeration? If you already have to use another object as a reference set and you're controlling the object list programmatically, then why not just use a normal string on that object?

**Comment by odi76** [comment]
Because of 2 important aspects:
- the built-in language support that platform provides for enum captions; and
- having a clear reference value (needed in expressions) which is validated in even building-time.

**Comment by odi76** [comment]
Please let me know, if you may reconsider your former decision based on such information. Otherwise I will not be able to apply this widget. It would be a shame because all other capabilities are very impressive and handy. Congrats!

**Comment by bsgriggs** [comment]
I'll take a look and see what I can do. I hadn't considered the use case for other languages.

It would be _possible_ to have the logic create a list of objects for each language. But I can see how that would get out of hand when it comes to querying.

**Comment by bsgriggs** [comment]
The bug fix has been deployed to the [Mendix Marketplace as version 1.5.0](https://marketplace.mendix.com/link/component/116917). Please let me know if you encounter any issues!

**Comment by odi76** [comment]
Thanks for the prompt action. I tested the v1.5.0 and my experience a little bit strange. The operation seems unstable. It sometimes works and sometimes does not. "Not work" means an empty selection list.
I could not figure out on what it depends on but somehow belongs to the processing time. In case of applying a time-consuming XPath constraint, the selection list is always presented correctly.

A repeatable scenario to "fix" the selection list:
0. The selection list is empty.
1. Clear the current value
2. Enter a searching pattern (min 3-4 characters)
3. Clear the value
4. The selection list is properly presented.

I tested with DB, XPath and MF sourcing. The result above was the same.

**Comment by bsgriggs** [comment]
Hmm I see, I will take a look.

**Comment by bsgriggs** [comment]
I believe I've fixed the issue, can you please download from the [lastest GitHub release](https://github.com/bsgriggs/mendix9-searchable-reference-selector/releases/download/v1.5.1/mendix.SearchableReferenceSelectorMxNine.mpk) and give it a test?

**Comment by odi76** [comment]
I tested and it seemed OK. Cool! Thanks a lot! I am looking forward to the published release.

Istvan

**Comment by bsgriggs** [comment]
wonderful! I've deployed to the marketplace as v1.5.1
