### ISSUE TITLE
Extra "autoselection list"

### ISSUE THREAD

**Issue by odi76** [bsgriggs/mendix9-searchable-reference-selector#7]
Hi Benjamin,

I face into a weird phenomenon in some specific usages of your widget. You can see some screenshots enclosed. You can see the "extra" selection list supporting typing value. It might be managed by browser (I use Chrome), but I could not figure out how. I tried to reproduce them with selecting values in the widget, but they were not cached for a next editing. Therefore I do not know for which widget usage it will occur again. In addition I do not know even how they can be deleted after they have been cached and started to present.

However this could be extremely disturbing, because it somehow belongs to the 'common name' value as well: you get the same autocomplete list via the whole application for the same common name value. That is, it is not limited only the same page. So this can result a very confusing data entries across the application. (e.g. you would like to select a colour and presented the user list (based on the user selection applied at another page with the same common name).

Could you check and share your thoughts?

Screenshots:

- <img width="227" alt="Screenshot_20221205_125309" src="https://user-images.githubusercontent.com/19372170/205631355-2155620d-ed48-4e86-8b5a-b3172f52f37b.png">
- <img width="227" alt="Screenshot_20221205_125309" src="https://user-images.githubusercontent.com/19372170/205631394-54e2b737-7fd4-4e96-83be-9c3635eca8ea.png">
- <img width="235" alt="Screenshot_20221205_125235" src="https://user-images.githubusercontent.com/19372170/205631427-0dd2517f-385c-4bb2-a2cb-6fa6723ec3bc.png">

Best,
Istvan

**Comment by bsgriggs** [comment]
fixed in GitHub release v1.5.4 (will upload to Marketplace after reviewing issue #8)
