### ISSUE TITLE
Roll-down selection for non-editable usage

### ISSUE THREAD

**Issue by odi76** [bsgriggs/mendix9-searchable-reference-selector#8]
Currently you can put the focus to a non-editable widget and then it rolls down the available selection list. Though you cannot edit the current value, it would be more friendly, if the list is not presented at all. Please consider this operation.

Screenshot:
<img width="339" alt="Screenshot_20221205_132831" src="https://user-images.githubusercontent.com/19372170/205637500-61d94cc0-31c7-46bc-abba-bb1856044a19.png">

**Comment by bsgriggs** [comment]
fix released to marketplace version 1.5.5
